name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 设置 JDK 11，使用 Adoptium 的 Temurin JDK 发行版
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'  # 使用 Temurin 代替 adoptopenjdk

    # 安装 Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v1
      with:
        api-level: 30         # 设置你需要的 Android API 级别
        build-tools-version: '30.0.3'  # 设置构建工具版本
        target: 'android-30'  # 设置目标 Android 版本

    # 设置 ANDROID_HOME 环境变量，使用 $GITHUB_ENV 文件
    - name: Set ANDROID_HOME environment variable
      run: echo "ANDROID_HOME=/home/runner/android" >> $GITHUB_ENV

    # 构建 APK（选择 Release 或 Debug）
    - name: Build APK
      run: ./gradlew assembleRelease   # 选择你需要的构建类型：assembleRelease 或 assembleDebug

    # 上传构建的 APK 文件
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: HookColorOS-apk
        path: app/build/outputs/apk/release/*.apk  # 根据项目的输出路径调整
